apiVersion: networking.istio.io/v1
kind: DestinationRule

metadata:
  name: app-service-mesh-dr

spec:
  host: app-service-mesh-svc.app.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      # consecutive5xxErrors: 10
      consecutiveGatewayErrors: 10
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
    loadBalancer:
      consistentHash:
        httpQueryParameterName: 'teste'
  subsets:
    - name: V1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: LEAST_CONN
    - name: V2
      labels:
        version: v2
      trafficPolicy:
        loadBalancer:
          simple: RANDOM
